---
- hosts: all
  become: yes
  vars:
    assets_base: ../../../files/zips
    application: blacklisting
    file_ext: sql
    install_location: /opt/netips/rules/update/cnc
    update_cmd: /usr/local/bin/cnclistupdate
  tasks:
    - name: create install dir
      file:
        path: "{{install_location}}"
        recurse: yes
        state: directory
    - name: copy zip file
      synchronize:
        src: "{{assets_base}}/{{application}}/{{version}}/ruleset-{{application}}-{{version}}.{{file_ext}}"
        dest: "{{install_location}}/"
    - name: run update command 
      shell:
        cmd: "{{update_cmd}} ruleset-{{application}}-{{version}}.{{file_ext}} {{version}}"
        chdir: "{{install_location}}"
