- name: install base package
  package:
    name:
      - apt-transport-https
      - unzip
      - clamav
      - python3
      - python3-pip
    state: present
    update_cache: yes
  become: yes
- name: install nodejs 14
  shell:
    cmd: curl -sL https://deb.nodesource.com/setup_14.x | bash -
  become: yes
- name: install nodejs 14 with apt
  package: 
    name:
      - nodejs
    state: present
    update_cache: yes
  become: yes
  ignore_errors: yes
- name: set hostname
  hostname:
    name: "{{inventory_hostname}}"
  become: yes
