- name: install configure file for metricbeat
  template:
    src: ../beats-templates/metricbeat.j2
    dest: /etc/metricbeat/metricbeat.yml
    mode: '0644'
  become: yes
- name: intall configure module files for metricbeat
  synchronize:
    src: ../beats-templates/metricbeat.modules.d/
    dest: /etc/metricbeat/modules.d/
    perms: yes
  become: yes
- name: chown of modules config files
  command: chown root:root -R /etc/metricbeat/modules.d
  become: yes

- name: install configure file for filebeat
  template:
    src: "../beats-templates/{{item}}.j2"
    dest: "/etc/filebeat/{{item}}.yml"
    mode: '0644'
  loop:
    - filebeat
    - filebeat.modsec
  become: yes
- name: prepare path.data and path.log for filebeat.modsec
  synchronize:
    src: ../beats-templates/empty
    dest: /var/log/filebeat.modsec
  become: yes
- name: prepare path.data for filebeat.modsec
  file:
    path: "{{item}}"
    state: directory
  become: yes
  loop:
    - /var/lib/filebeat.modsec
    - /var/log/modsec
- name: install filebeat.modsec service
  synchronize:
    src: ../beats-templates/filebeat.modsec.service
    dest: /etc/systemd/system/
  become: yes
