- name: realtime-protection source code
  synchronize:
    src: ../realtime-protection
    dest: /opt/
  become: yes
- name: realtime-protection pip install -r requirements.txt
  shell:
    chdir: /opt/realtime-protection
    cmd: pip3 install -r requirements.txt
  become: yes
- name: install realtime-protection service
  synchronize: 
    src: ../realtime-protection/realtime-protection.service
    dest: /etc/systemd/system/
  become: yes
