---
- hosts: all
  become: yes
  vars:
    assets_base: ../../../files/zips
    application: idssystem
    install_location: /opt/netips/rules/update
    update_cmd: /usr/local/bin/updaterules
  tasks:
    - name: create install dir
      file:
        path: "{{install_location}}"
        recurse: yes
        state: directory
    - name: copy zip file
      synchronize:
        src: "{{assets_base}}/{{application}}/{{version}}/ruleset-{{application}}-{{version}}.zip"
        dest: "{{install_location}}/"
    - name: run update command 
      shell:
        cmd: "{{update_cmd}} ruleset-{{application}}-{{version}}.zip {{version}}"
        chdir: "{{install_location}}"
